pipelines:
  branches:
    development:
      - step:
          name: Clean up
          image: drud/ddev-webserver:v1.16.1
          script:
            - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
            - git fetch --unshallow
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            - git fetch origin
            - git checkout master
            - git merge -s ours development --no-commit --no-ff
            - export LATEST_TAG=$(git describe --abbrev=0 --tags | grep -Po "(\d+\.)+\d+")
            - export GIT_LOG=$(git log "v$LATEST_TAG"..HEAD --pretty=format:"%s")
            - git checkout development .
            - export TYPO3_EXT_VERSION=$(cat ext_emconf.php | grep version* | grep -Po "(\d+\.)+\d+")
            - rm -rf Tests .editorconfig .gitignore .ddev bitbucket-pipelines.yml composer.lock package.json tsconfig.json webpack.*.js  Gruntfile.js vendor public Build package-lock.json bin node_modules Resources/Private/TypeScript Resources/Private/Scss config .phpstorm.meta.php
            - git add */.*
            - 'if [[ $(git status --porcelain --untracked-files=no | wc -l) -gt "0" ]]; then git commit -a -m "build: $BITBUCKET_COMMIT_SHORT" --message "$GIT_LOG" || true; fi'
            - 'if [ "$TYPO3_EXT_VERSION" != "$LATEST_TAG" ]; then git tag -a "v$TYPO3_EXT_VERSION" -m ""; fi'
            - git push origin master --tags
