name: test-build-release

on:
  push:
    branches:
      - development

jobs:

  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:lint

  php-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:fixer

  php-stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:stan

  release:
    needs:
      - php-lint
      - php-fixer
      - php-stan
    uses: maikschneider/reusable-workflows/.github/workflows/release-typo3-extension.yml@main
    secrets:
      teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
    with:
      base-branch: master
